"use client";

import Link from "next/link";
import { Activity, ArrowLeft, Clock3, Database, Download, Radar, RefreshCw, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { ThemeToggle } from "./theme-toggle";

type Run = { run_id: string; answer: string; task: string; inference_mode: string; status: string; created_at: string; model: { id: string; version: string }; confidence: { value: number; method: string; calibrated: boolean }; warnings: string[]; trace: Array<{ stage: string; status: string; detail: string }> };

export function RunsClient() {
  const [runs, setRuns] = useState<Run[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const api = process.env.NEXT_PUBLIC_SATQUERY_API_URL ?? "http://localhost:8000";
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`${api}/api/v1/runs`); if (!response.ok) throw new Error(); setRuns(await response.json()); } catch { setError("The SatQuery API is offline. Start it on port 8000 to view persisted runs."); } finally { setLoading(false); } }, [api]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  return <main className="runs-page"><header className="workspace-header glass-bar"><Link href="/workspace" className="icon-button" aria-label="Back to workspace"><ArrowLeft /></Link><div className="workspace-title"><span className="brand-mark"><Radar /></span><div><strong>Run archive</strong><small>Reproducible analysis history</small></div></div><div className="workspace-actions"><button className="tool-button" onClick={load}><RefreshCw /> Refresh</button><ThemeToggle /></div></header><section className="runs-shell"><div className="runs-heading"><div><span className="kicker">Persistent investigations</span><h1>Analysis runs</h1><p>Inspect model routing, confidence policy, warnings, and every processing stage.</p></div><div className="run-count"><Database /><strong>{runs.length}</strong><span>stored runs</span></div></div>{loading && <div className="runs-empty"><Activity className="scanning" /><h2>Loading run history</h2></div>}{error && <div className="runs-empty"><Clock3 /><h2>API unavailable</h2><p>{error}</p></div>}{!loading && !error && !runs.length && <div className="runs-empty"><Database /><h2>No completed runs yet</h2><p>Run an analysis from the workspace and it will appear here.</p><Link className="button" href="/workspace">Open workspace</Link></div>}<div className="runs-list">{runs.map(run => <article className="run-card" key={run.run_id}><div className="run-card-top"><div><span className={`run-mode ${run.inference_mode}`}>{run.inference_mode}</span><span className="run-status">{run.status}</span><h2>{run.task} · {run.model.id}</h2><code>{run.run_id}</code></div><div className="run-confidence"><strong>{Math.round(run.confidence.value * 100)}%</strong><span>{run.confidence.calibrated ? "calibrated" : "uncalibrated"}</span></div></div><p>{run.answer}</p><div className="run-trace">{run.trace.map(item => <div key={item.stage}><ShieldCheck /><strong>{item.stage}</strong><span>{item.detail}</span></div>)}</div><div className="run-footer"><span>{run.created_at}</span><a className="report-button" href={`${api}/api/v1/runs/${run.run_id}/report`}><Download /> Report</a></div></article>)}</div></section></main>;
}
